version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: kitsune-postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kitsune:/var/lib/postgresql/data

volumes:
  kitsune:
