# Define the base image
FROM astral/uv:python3.14-trixie

ENV WEAVIATE_URL=http://ww8.index.k8s.bio.scai.fraunhofer.de
ENV OLLAMA_URL=http://nomic-embed-text.ollama.k8s.bio.scai.fraunhofer.de

WORKDIR /api

COPY . /api/

RUN uv sync --no-dev --no-cache

EXPOSE 80

CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
