# Define the base image
FROM astral/uv:python3.14-trixie

WORKDIR /api

COPY . /api/

RUN uv sync --no-dev --no-cache

EXPOSE 80

# API entry point
CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
